swagger: "2.0"
info:
  version: 1.0.0
  title: "FIT ECO"
  description: A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
definitions:
  Brand: #Имя очереди api.fit.power-bi-collector.brand.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  Client: #Контрагенты имя очереди: api.fit.power-bi-collector.customers.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      IsFolder:
        type: boolean
        description: Признак является ли папкой, возможно потребуется для построения иерархии
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
      Pol:
        type: string
        description: Пол клиента (Мужской,Женский)
      DOB:
        type: string #dateTime
        description: Дата рождения
      UrFizLico:
        type: string
        description: Юр физ лицо (ЮрЛицо, ФизЛицо)
  GoodsGroup: #Номенклатурные группы имя очереди: api.fit.power-bi-collector.goods.groups.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  GoodsType: #Вид номенклатуры Имя очереди: api.fit.power-bi-collector.goods.types.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  PlanOfSTO: #План СТО Имя очереди: api.fit.power-bi-collector.plan.of.sto.change plan.of.sto.change
    type: object
    properties:
      Date:
        type: string #dateTime
      STOGUID:
        $ref: '#/definitions/STO'
      Cash:
        type: integer
        description: Выручка
      Profit:
        type: integer
        description: Доход
  Sales: #Продажи/Возвраты имя очереди: api.fit.power-bi-collector.sales.goods.services
    type: object
    properties:
      GUID:
        type: string
      Date:
        type: string #dateTime
      Number:
        type: string
        description: Номер документа
      STO:
        $ref: '#/definitions/STO'
      UserGUID:
        $ref: '#/definitions/User'
      Operation:
        type: string
        description: Вид операции (Продажа, Возврат)
      OrderDate:
        type: string #dateTime
        description: Дата заказ-наряда
      OrderNumber:
        type: string
        description: Номер документа заказ-наряда
      Goods:
        description: Товары
        type: array
        items:
          type: object
          properties:
            GoodsGroupGUID:
              $ref: '#/definitions/GoodsGroup'
            BrandGUID:
              $ref: '#/definitions/Brand'
            Count:
              type: integer
            Price:
              type: integer
            SummaWithoutDiscount:
              type: integer
            Discount:
              type: integer
      Services:
        description: Услуги
        type: array
        items:
          type: object
          properties:
            ServiceGUID:
              $ref: '#/definitions/Service'
            Count:
              type: integer
            Price:
              type: integer
            SummaWithoutDiscount:
              type: integer
            Discount:
              type: integer
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  Service: #НормоЧасыМоделей имя очереди: api.fit.power-bi-collector.services.change
    type: object
    properties:
      GUID:
        type: string
      Number:
        type: string
        description: Код услуги
      Name:
        type: string
      ParentGUID:
        type: string
        description: Код услуги родителя (папки)
      ParentName:
        type: string
        description: Наименование услуги родителя (папки)
      ParentNumber:
        type: string
        description: Код услуги родителя (папки)
      IsFolder:
        type: boolean
        description: Признак является ли папкой, возможно потребуется для построения иерархии
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  STO: #Имя очереди: api.fit.power-bi-collector.sto.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string #
      IsFolder:
        type: boolean
        description: Признак является ли папкой, возможно потребуется для построения иерархии
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
      TerritoryGUID:
        $ref: '#/definitions/Territory'
      TerritoryName:
        type: string
        description: Наименование Филиала к которому относится СТО
  Territory: #Имя очереди api.fit.power-bi-collector.filial.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
  User: #Пользователи имя очереди: api.fit.power-bi-collector.users.change
    type: object
    properties:
      GUID:
        type: string
      Name:
        type: string
      IsFolder:
        type: boolean
        description: Признак является ли папкой, возможно потребуется для построения иерархии
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
      ArrayOfSTO:
        type: array
        items:
            $ref: '#/definitions/STO'
  WorkOrders: #Заказ-наряды имя очереди api.fit.power-bi-collector.work.order
    type: object
    properties:
      GUID:
        type: string
      Date:
        type: string #dateTime
      Number:
        type: string
        description: Номер документа
      STOGUID:
        $ref: '#/definitions/STO'
      ClientGUID:
        $ref: '#/definitions/Client'
      Type:
        type: string
        description: Вид Заказ-наряда (Ремонт, Продажа, Быстрое обслуживание, Гарантийный ремонт)
      DiscountGUID:
        type: string
        description: Идентификатор акции, пока в выгрузке ее нет, но в будущем появится
      DateStart:
        type: string #dateTime
        description: Дата начала работ
      DateEnd:
        type: string #dateTime
        description: Дата окончания работ
      DateAccept:
        type: string #dateTime
        description: Дата принятия клиента
      DeletionMark:
        type: boolean
        description: Признак пометки на удаление
